/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/room.glb -t -r /models -o src/scene/RoomModel.tsx
Author: Waven (https://sketchfab.com/wavenquack24)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-gaming-bedroom-3799700f186a4104ae570ea0c92a82fd
Title: Low Poly Gaming Bedroom

Manually modified:
  - Fixed useGLTF path to '/models/room.glb'
  - Removed unused React import (new JSX transform)
  - Removed undefined GLTFAction type
  - Added InteractiveObject wrappers for each portfolio section:
      Profile → Bed
      Skills  → PC Case
      Works   → Monitor
      Contact → Book
*/

import type * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three/examples/jsm/loaders/GLTFLoader.js'
import InteractiveObject from './objects/InteractiveObject'

type GLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh
    Object_5: THREE.Mesh
    Object_6: THREE.Mesh
    Object_7: THREE.Mesh
    Object_8: THREE.Mesh
    Object_9: THREE.Mesh
    Object_10: THREE.Mesh
    Object_11: THREE.Mesh
    Object_12: THREE.Mesh
    Object_13: THREE.Mesh
    Object_15: THREE.Mesh
    Object_16: THREE.Mesh
    Object_17: THREE.Mesh
    Object_18: THREE.Mesh
    Object_19: THREE.Mesh
    Object_20: THREE.Mesh
    Object_22: THREE.Mesh
    Object_23: THREE.Mesh
    Object_25: THREE.Mesh
    Object_27: THREE.Mesh
    Object_28: THREE.Mesh
    Object_30: THREE.Mesh
    Object_31: THREE.Mesh
    Object_32: THREE.Mesh
    Object_33: THREE.Mesh
    Object_34: THREE.Mesh
    Object_35: THREE.Mesh
    Object_36: THREE.Mesh
    Object_37: THREE.Mesh
    Object_38: THREE.Mesh
    Object_39: THREE.Mesh
    Object_40: THREE.Mesh
    Object_42: THREE.Mesh
    Object_43: THREE.Mesh
    Object_44: THREE.Mesh
    Object_46: THREE.Mesh
    Object_47: THREE.Mesh
    Object_48: THREE.Mesh
    Object_50: THREE.Mesh
    Object_51: THREE.Mesh
    Object_53: THREE.Mesh
    Object_54: THREE.Mesh
    Object_56: THREE.Mesh
    Object_57: THREE.Mesh
    Object_58: THREE.Mesh
    Object_59: THREE.Mesh
    Object_60: THREE.Mesh
    Object_61: THREE.Mesh
    Object_63: THREE.Mesh
    Object_64: THREE.Mesh
    Object_65: THREE.Mesh
    Object_66: THREE.Mesh
    Object_68: THREE.Mesh
    Object_69: THREE.Mesh
  }
  materials: {
    Baseboard: THREE.MeshStandardMaterial
    Ceiling: THREE.MeshStandardMaterial
    Floor: THREE.MeshStandardMaterial
    Wall: THREE.MeshStandardMaterial
    LightSwitch: THREE.MeshStandardMaterial
    DoorHandle: THREE.MeshStandardMaterial
    Door: THREE.MeshStandardMaterial
    Planks: THREE.MeshStandardMaterial
    Hole: THREE.MeshStandardMaterial
    Glass: THREE.MeshStandardMaterial
    Pillow: THREE.MeshStandardMaterial
    Wood1: THREE.MeshStandardMaterial
    Bedsheets: THREE.MeshStandardMaterial
    Blanket: THREE.MeshStandardMaterial
    InsideBlanket: THREE.MeshStandardMaterial
    BedHead: THREE.MeshStandardMaterial
    Wood2: THREE.MeshStandardMaterial
    Chair: THREE.MeshStandardMaterial
    Plastic: THREE.MeshStandardMaterial
    Case: THREE.MeshStandardMaterial
    Case2: THREE.MeshStandardMaterial
    Fans: THREE.MeshStandardMaterial
    material: THREE.MeshStandardMaterial
    Motherboard: THREE.MeshStandardMaterial
    BlueLight: THREE.MeshStandardMaterial
    PurpleLight: THREE.MeshStandardMaterial
    Nanoleaf: THREE.MeshStandardMaterial
    Plug: THREE.MeshStandardMaterial
    Metal: THREE.MeshStandardMaterial
    Monitor: THREE.MeshStandardMaterial
    Cable: THREE.MeshStandardMaterial
    Keyboard: THREE.MeshStandardMaterial
    Keycaps: THREE.MeshStandardMaterial
    Mousepad: THREE.MeshStandardMaterial
    Mouse: THREE.MeshStandardMaterial
    LightBulbBase: THREE.MeshStandardMaterial
    BookCover: THREE.MeshStandardMaterial
    Pages: THREE.MeshStandardMaterial
  }
}

export function RoomModel() {
  const { nodes, materials } = useGLTF('/models/room.glb') as unknown as GLTFResult
  return (
    <group dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.913}>
        <group rotation={[Math.PI / 2, 0, 0]}>

          {/* ── 部屋の構造（非インタラクティブ）── */}
          <group rotation={[0, -Math.PI / 2, 0]}>
            <mesh geometry={nodes.Object_4.geometry} material={materials.Baseboard} />
            <mesh geometry={nodes.Object_5.geometry} material={materials.Ceiling} />
            <mesh geometry={nodes.Object_6.geometry} material={materials.Floor} />
            <mesh geometry={nodes.Object_7.geometry} material={materials.Wall} />
            <mesh geometry={nodes.Object_8.geometry} material={materials.LightSwitch} />
            <mesh geometry={nodes.Object_9.geometry} material={materials.DoorHandle} />
            <mesh geometry={nodes.Object_10.geometry} material={materials.Door} />
            <mesh geometry={nodes.Object_11.geometry} material={materials.Planks} />
            <mesh geometry={nodes.Object_12.geometry} material={materials.Hole} />
            <mesh geometry={nodes.Object_13.geometry} material={materials.Glass} />
          </group>

          {/* ── Profile: ベッド ── */}
          <InteractiveObject sectionId="profile">
            <group position={[2.529, 0.623, 1.252]} rotation={[0, Math.PI / 2, 0]} scale={1.085}>
              <mesh geometry={nodes.Object_15.geometry} material={materials.Pillow} />
              <mesh geometry={nodes.Object_16.geometry} material={materials.Wood1} />
              <mesh geometry={nodes.Object_17.geometry} material={materials.Bedsheets} />
              <mesh geometry={nodes.Object_18.geometry} material={materials.Blanket} />
              <mesh geometry={nodes.Object_19.geometry} material={materials.InsideBlanket} />
              <mesh geometry={nodes.Object_20.geometry} material={materials.BedHead} />
            </group>
          </InteractiveObject>

          {/* ── デスク（棚・非インタラクティブ）── */}
          <group position={[2.472, 0.511, -1.771]} rotation={[0, -Math.PI / 2, 0]}>
            <mesh geometry={nodes.Object_22.geometry} material={materials.Wood1} />
            <mesh geometry={nodes.Object_23.geometry} material={materials.Wood2} />
          </group>

          {/* ── デスク天板 Object_25（非インタラクティブ）── */}
          <mesh
            geometry={nodes.Object_25.geometry}
            material={materials.Wood1}
            position={[-2.479, 0.612, -1.76]}
            rotation={[0, -Math.PI / 2, 0]}
          />

          {/* ── チェア（非インタラクティブ）── */}
          <group position={[-2.53, 0.756, -1.228]} rotation={[0, Math.PI / 2, 0]}>
            <mesh geometry={nodes.Object_27.geometry} material={materials.Chair} />
            <mesh geometry={nodes.Object_28.geometry} material={materials.Plastic} />
          </group>

          {/* ── Skills: PCケース ── */}
          <InteractiveObject sectionId="skills">
            <group position={[-1.523, 0.448, -1.759]} rotation={[0, -Math.PI / 2, 0]}>
              <mesh geometry={nodes.Object_30.geometry} material={materials.Case} />
              <mesh geometry={nodes.Object_31.geometry} material={materials.Case2} />
              <mesh geometry={nodes.Object_32.geometry} material={materials.Glass} />
              <mesh geometry={nodes.Object_33.geometry} material={materials.Fans} />
              <mesh geometry={nodes.Object_34.geometry} material={materials.material} />
              <mesh geometry={nodes.Object_35.geometry} material={materials.Motherboard} />
              <mesh geometry={nodes.Object_36.geometry} material={materials.BlueLight} />
              <mesh geometry={nodes.Object_37.geometry} material={materials.PurpleLight} />
              <mesh geometry={nodes.Object_38.geometry} material={materials.Nanoleaf} />
              <mesh geometry={nodes.Object_39.geometry} material={materials.Plug} />
              <mesh geometry={nodes.Object_40.geometry} material={materials.Metal} />
            </group>
          </InteractiveObject>

          {/* ── Works: モニター ── */}
          <InteractiveObject sectionId="works">
            <group position={[-2.53, 1.485, -2.006]}>
              <mesh geometry={nodes.Object_42.geometry} material={materials.Monitor} />
              <mesh geometry={nodes.Object_43.geometry} material={materials.BlueLight} />
              <mesh geometry={nodes.Object_44.geometry} material={materials.Cable} />
            </group>
          </InteractiveObject>

          {/* ── キーボード（非インタラクティブ）── */}
          <group position={[-2.71, 1.036, -1.559]}>
            <mesh geometry={nodes.Object_46.geometry} material={materials.Keyboard} />
            <mesh geometry={nodes.Object_47.geometry} material={materials.BlueLight} />
            <mesh geometry={nodes.Object_48.geometry} material={materials.Keycaps} />
          </group>

          {/* ── マウスパッド（非インタラクティブ）── */}
          <group position={[-2.445, 1.001, -1.564]}>
            <mesh geometry={nodes.Object_50.geometry} material={materials.Mousepad} />
            <mesh geometry={nodes.Object_51.geometry} material={materials.PurpleLight} />
          </group>

          {/* ── マウス（非インタラクティブ）── */}
          <group position={[-2.001, 1.034, -1.57]}>
            <mesh geometry={nodes.Object_53.geometry} material={materials.Mouse} />
            <mesh geometry={nodes.Object_54.geometry} material={materials.BlueLight} />
          </group>

          {/* ── ナノリーフ（非インタラクティブ）── */}
          <group position={[0.133, 1.2, -2.24]}>
            <mesh geometry={nodes.Object_56.geometry} material={materials.Nanoleaf} />
            <mesh geometry={nodes.Object_57.geometry} material={materials.BlueLight} />
            <mesh geometry={nodes.Object_58.geometry} material={materials.Plug} />
            <mesh geometry={nodes.Object_59.geometry} material={materials.Metal} />
            <mesh geometry={nodes.Object_60.geometry} material={materials.Cable} />
            <mesh geometry={nodes.Object_61.geometry} material={materials.PurpleLight} />
          </group>

          {/* ── 天井ライト（非インタラクティブ）── */}
          <group position={[0, 3.374, 0]}>
            <mesh geometry={nodes.Object_63.geometry} material={materials.Metal} />
            <mesh geometry={nodes.Object_64.geometry} material={materials.PurpleLight} />
            <mesh geometry={nodes.Object_65.geometry} material={materials.BlueLight} />
            <mesh geometry={nodes.Object_66.geometry} material={materials.LightBulbBase} />
          </group>

          {/* ── Contact: 本 ── */}
          <InteractiveObject sectionId="contact">
            <group position={[2.014, 1.227, -1.909]} rotation={[Math.PI, -1.388, Math.PI]}>
              <mesh geometry={nodes.Object_68.geometry} material={materials.BookCover} />
              <mesh geometry={nodes.Object_69.geometry} material={materials.Pages} />
            </group>
          </InteractiveObject>

        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/room.glb')
